# Generated by Django 4.1.5 on 2023-01-23 20:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner', models.FileField(upload_to='media/img_post')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('resume', models.TextField(max_length=499)),
                ('content', models.TextField()),
                ('img_post', models.FileField(upload_to='media/post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth', models.ForeignKey(default=django.contrib.auth.models.User, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('P', 'Programador'), ('D', 'Designer'), ('N', 'Faço nada'), ('C', 'Comedor de casadas')], default='N', max_length=2)),
                ('image_perfil', models.FileField(upload_to='Perfil_User')),
                ('bio', models.TextField(max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='Blog.post')),
            ],
        ),
    ]
