# Generated by Django 4.1.5 on 2023-01-23 19:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('P', 'Programador'), ('D', 'Designer'), ('N', 'Faço nada'), ('C', 'Comedor de casadas')], default='N', max_length=2)),
                ('image_perfil', models.FileField(upload_to='Perfil_User')),
                ('bio', models.TextField(max_length=400)),
                ('User', models.ForeignKey(default=django.contrib.auth.models.User, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
